export const USER_ROLES = ["ROLE_SUPERVISOR", "ROLE_WORKER"];
export const ROLE_GROUPS = {
    ADMIN: ["ROLE_ADMIN"],
    SUPERVISOR: ["ROLE_ADMIN", "ROLE_SUPERVISOR"],
    WORKER: ["ROLE_ADMIN", "ROLE_WORKER", "ROLE_SUPERVISOR"]
}